# Generated by Django 4.2 on 2023-05-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorys',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categoryf',
            new_name='category',
        ),
    ]
