# Generated by Django 4.2 on 2023-05-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_rename_category_categorys_rename_product_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorys',
            old_name='category_name',
            new_name='category',
        ),
    ]
