# Generated by Django 4.2 on 2023-05-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_rename_category_name_categorys_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorys',
            old_name='category',
            new_name='c_name',
        ),
    ]
